php練習課題３の提出
shiraosa/quelcode-php pull request #3
Opened 2020-06-02 08:21 UTC by shiraosa

やったこと
・GETパラメータ[target]から1以上の整数を受け取り、既にデータベースに保存されている数値の羅列から、足してその数になる組み合わせを探す関数の実装。
・HTTP レスポンスステータスコード[400]返却の実装

再帰関数で全組み合わせを取得する方法ではなく、最初に思いついたDBから受け取った配列をtargetと比較していき合計値がtargetになる組み合わせをtargetと数値の差などを用いて探し保存する方法にしました。

2020-06-02 08:50 UTC, choimake reviewed
動作要件でいくつか満たせていないところや、コードの書き方についてコメントしていますので確認と修正お願いします。

2020-06-02 08:50 UTC, choimake commented on html/php-pre-challenge3/index.php
> +}
「もしデータベースに接続できない場合は、HTTP レスポンスステータスコード[500]で返却してください。」
こちらの動作要件が満たせていないので、実装お願いします。

2020-06-02 08:50 UTC, choimake commented on html/php-pre-challenge3/index.php
> +}
「GETパラメータ[target]値が1以上の整数ではない場合は、HTTP レスポンスステータスコード[400]で返却してください」のうちtargetに「01」が渡された時に400エラーになっていません。

カリキュラムを確認の上、01のような頭に0がついた値が渡された時にも400エラーを返却するようにしてください。

2020-06-02 08:50 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    $db = new PDO("$dsn", "$dbuser", "$dbpassword");
`"$dsn"`などは「"」で囲わなくても動作すると思います。

2020-06-02 08:50 UTC, choimake commented on html/php-pre-challenge3/index.php
> +rsort($value);//降順が必須
降順へのソートはDBからデータを取得する際に、降順で取得するよう指定してみてください。
「DB取得->phpでソート」より「DBで降順で取得」の方が動作が早いので。

2020-06-02 08:50 UTC, choimake commented on html/php-pre-challenge3/index.php
> +for($i = 0; $i < count($value); $i++){
`count`はfor文の外で実行するようにしましょう。
その方が動作が早いです。

2020-06-02 08:50 UTC, choimake commented on html/php-pre-challenge3/index.php
> +    global $check;//取りこぼしがないか確認する変数
グローバル変数は保守性の面で、なるべく使わない方がいい変数なので、一度グローバル変数なしで実装できないかどうかチャレンジしてみてください。

2020-06-03 03:20 UTC, shiraosa commented on html/php-pre-challenge3/index.php
> +}
実装しました。

2020-06-03 03:21 UTC, shiraosa commented on html/php-pre-challenge3/index.php
> +}
`substr`で先頭の0を判定する方法に変更しました。

2020-06-03 03:21 UTC, shiraosa commented on html/php-pre-challenge3/index.php
> +    $db = new PDO("$dsn", "$dbuser", "$dbpassword");
修正しました。

2020-06-03 03:22 UTC, shiraosa commented on html/php-pre-challenge3/index.php
> +rsort($value);//降順が必須
`ORDER BY`で降順を指定しました。

2020-06-03 03:23 UTC, shiraosa commented on html/php-pre-challenge3/index.php
> +    global $check;//取りこぼしがないか確認する変数
関数にデフォルト値を設定し、`return`で`$json`を返す仕様に変更しました。

2020-06-03 03:26 UTC, shiraosa commented on html/php-pre-challenge3/index.php
> +for($i = 0; $i < count($value); $i++){
`$value_count`に代入してfor文に組み込みました

2020-06-03 03:30 UTC, shiraosa commented
指摘箇所の修正をしました。

- データベースに接続できなかった場合のHTTPレスポンスコードの実装

- 01の判定に`substr`を使用

- 不要な""の削除

- `ORDER BY`で降順を指定

- `count`を変数に代入してfor文で使用

- グローバル変数を削除、関数にデフォルト値を設定し、returnで$jsonを返す仕様に変更

2020-06-03 09:04 UTC, yusaku-inamura requested changes
メインの組み合わせ探索ロジック、実はリスト内の幾つの値を組み合わせることで成立するのか?という点に着目して書くともう少し簡潔に書けると思うのですが、一応仕様は満たしているみたいなのでOKです 🙆‍♂️ 
(読みにくさという点で実務ではちょっと困りますが、このロジックで一通り完成に漕ぎ着けたこと自体はすごい)
これからはロジックをより簡単に書くにはどうすればいいか?という点を意識して書けるととより良くなっていくと思います。

細部に指摘してるので、仕上げてしまいましょう 👍

2020-06-03 09:04 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +if(! ctype_digit($limit) || substr("$limit",0,1)==0){
`substr("$limit",0,1)==0` ここもし意識しているなら全然問題ないのですが、あまり数値の正当性をチェックするのに文字列として先頭を切り出して〜みたいなやり方はあまり一般的には行われないですかね。
今回の例で言えば正規表現を使用すれば一発ですし、もし0始まりの数値を判別したいだけなのであれば `filter_var()` 関数が使えますので。
ただ一応動作要件は満たせているのでここは今回は良しとします。

それと比較に `==` を使うのは基本的にNGです。
どうしても使用しなくてはいけない場合も、そもそもロジックが間違えていないかを見直すべきですね。

また、 `"$limit"` これダブルクォーテーションを使用している理由ってなんですかね? 🤔

2020-06-03 09:04 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +$prechallenge3 = $dbdata -> fetchAll();
アロー演算子の前後にスペースつけたりつけなかったりとコードのスタイルがバラバラです。
必ず統一するようにしましょう。
ちなみに一般的にはスペースはつけないことが多いですね。
他のコーディングスタイルについてもしっかり統一されているか見直してください。

2020-06-03 09:04 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +settype($limit, "int");
対象の型に変換できることがわかっている場合にはあまり `settype()` を使うことはないですかね・・・。
変換の結果が問題ないかどうかを戻り値でうけとって確認するみたいな時に使うことが多いかもです。
(そもそもそれ自体あまりないですが)
今回みたいに数値のバリデーションチェック後に使うものであれば `(int) $limit` で事足りるからですね。
要件としては問題ないのでこのままでOKです

2020-06-03 09:04 UTC, yusaku-inamura commented on html/php-pre-challenge3/index.php
> +$value = array_column($prechallenge3, "value");
これは単数系ですが一つの値を表すものではないので変数名として不適切な気がします。
複数形にするべきでしょう

2020-06-04 01:35 UTC, shiraosa commented on html/php-pre-challenge3/index.php
> +$value = array_column($prechallenge3, "value");
$valueを$valuesに変更しました。

2020-06-04 01:36 UTC, shiraosa commented on html/php-pre-challenge3/index.php
> +if(! ctype_digit($limit) || substr("$limit",0,1)==0){
"03"などで動作確認をした後にそのまま`"$limit"`としてしまいました。""を削除しました。また0を`"0"`にして`===`を使用しました。

2020-06-04 01:37 UTC, shiraosa commented on html/php-pre-challenge3/index.php
> +$prechallenge3 = $dbdata -> fetchAll();
スペースをつけるで統一しました。

2020-06-04 02:02 UTC, shiraosa commented
指摘箇所の修正をしました。

- ""の削除

- 0を"0"にして==を===に変更

- スペースの統一

- $valueを$valuesに変更

2020-06-04 05:49 UTC, Yuzunoha commented
下記の観点において動作要件を満たしていないようなので確認してください～

- targetに 26 を指定したときに [1,5,7,13] が出ない
- targetに 35 を指定したときに [1,3,7,11,13] が出ない

2020-06-04 06:23 UTC, shiraosa commented
たびたび申し訳ございません。読みにくいコードを書いたこと非常に反省しております。

`$i`が増加した際に`$check`を削除しなかったために判定がおかしくなっていました。`unset($check)`を追加することで解消されました。

> 下記の観点において動作要件を満たしていないようなので確認してください～
> 
> * targetに 26 を指定したときに [1,5,7,13] が出ない
> * targetに 35 を指定したときに [1,3,7,11,13] が出ない

2020-06-04 08:12 UTC, Yuzunoha commented
アルゴリズムに果敢に取り組んでいてよいと思います！！

下記の観点で動作要件を満たしていないようなので確認してください～

- targetに 38 を指定したときに [3,5,13,17] が出ない
- targetに 39 を指定したときに [1,3,5,13,17] が出ない
- targetに 40 を指定したときに [3,5,13,19] が出ない

2020-06-08 03:28 UTC, shiraosa commented
> 下記の観点で動作要件を満たしていないようなので確認してください～
> 
> * targetに 38 を指定したときに [3,5,13,17] が出ない
> * targetに 39 を指定したときに [1,3,5,13,17] が出ない
> * targetに 40 を指定したときに [3,5,13,19] が出ない

↑の原因と思しき箇所は分かったのですが解決方法が思いつかなく、これ以上複雑にすると自分でも理解できなくなりそうだったので、[https://stabucky.com/wp/archives/2188](https://stabucky.com/wp/archives/2188)　の組み合わせ取得関数を利用して全組み合わせを取得したのちに合計値が$limitになる組み合わせを得る方法に変更しました。

2020-06-08 03:53 UTC, Yuzunoha approved these changes
OKです！！承認しました！！！

2020-06-18 01:14 UTC, merged